# Generated by Django 4.2.11 on 2024-04-21 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Donar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Donar_name', models.CharField(max_length=50, null=True)),
                ('Donar_email', models.EmailField(max_length=50, null=True)),
                ('Donar_age', models.IntegerField(null=True)),
                ('Donar_bloodGroup', models.CharField(max_length=10, null=True)),
                ('Donar_Unit', models.IntegerField(null=True)),
                ('Donar_dat', models.IntegerField(null=True)),
                ('Donar_disease', models.CharField(max_length=50, null=True)),
            ],
        ),
    ]
