# Generated by Django 4.2.11 on 2024-04-22 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bloodapp', '0002_patient'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patientss',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Patientss_name', models.CharField(max_length=50, null=True)),
                ('Patientss_email', models.EmailField(max_length=50, null=True)),
                ('Patientss_age', models.IntegerField(null=True)),
                ('Patientss_bloodGroup', models.CharField(max_length=10, null=True)),
                ('Patientss_Unit', models.IntegerField(null=True)),
                ('Patientss_dat', models.IntegerField(null=True)),
                ('Patientss_disease', models.CharField(max_length=50, null=True)),
            ],
        ),
    ]
